server:
  port: 8765

eureka:
  client:
    service-url: #registrando no eureka
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: gateway-cloud
    
  cloud:
    gateway: 
      discovery:
        locator:
          enabled: true
      routes:
      - id: conta-service
        uri: lb://conta-service
        predicates:
        - Path=/conta-service/**
        
      - id: cliente-service
        uri: lb://cliente-service
        predicates:
        - Path=/cliente-service/**
        
      - id: transacao-service
        uri: lb://transacao-service
        predicates:
        - Path=/transacao-service/**
